### ISSUE TITLE
Resource limit exceeded when deploying

### ISSUE THREAD

**Issue by franciscocpg** [amplify-education/serverless-log-forwarding#15]
I'm getting this error frequently (and intermittent) when trying to deploy a serverless project using this plugin.

```
Serverless: Operation failed!

 

  Serverless Error ---------------------------------------

 

  An error occurred: SubscriptionFilterSaveDashcourse - Resource limit exceeded..
```

Any ideas about the reason?

**Comment by sidgonuts** [comment]
This should be closed with #15. Thanks for bringing this to our attention!
