### ISSUE TITLE
Serverless 2.x

### ISSUE THREAD

**Issue by rogueturnip** [amplify-education/serverless-log-forwarding#55]
Is this plugin going to get a refresh to work with serverless framework 2.x?

**Comment by aoskotsky-amplify** [comment]
Yes it will. We will try to get to it soon

**Comment by rogueturnip** [comment]
Just following up on this to see if the module is going to evolve or we should look for a different solution.

Thanks!

**Comment by aoskotsky-amplify** [comment]
Sorry for the long delay. We are going to take a look at this next week. We should have a new version with this soon

**Comment by rddimon** [comment]
Hi @rogueturnip 

We have added 3.x support and I believe it should work with the 2.x too.
With the 
```
"peerDependencies": {
    "serverless": "<4"
  },
```

Please try our latest version and let us know
